#!/usr/bin/env python3
import csv, os, random
import pandas as pd
PROJECT = "/mnt/c/Users/Akshith/leakage_resilient_password_storage"
IN = os.path.join(PROJECT, "tests", "john_logs", "honey_fake_outputs.csv")
# IMPORTANT: your honey implementation must be importable; adapt these calls to your API.
# For this script we'll assume CSV has columns: real_password, cipher_repr, real_index, and we have function honey_decrypt_by_index(cipher_repr, i)
# If your CSV is different, you'll need to adapt to how you stored honey payloads.

# For demonstration we'll simulate attacker guesses against a single record:
df = pd.read_csv(IN, encoding="utf-8", low_memory=False)

# If you have a real password for which decoys were generated, put it here:
# We'll assume the CSV was generated by trying wrong keys and saving wrong key, fake_output.
# So instead we'll simulate: attacker picks a wrong index => we check proportion of wrong indices producing decoy != real.
# If you have structured honey payload per user (encrypted candidates + real index) use that mapping instead.

# For a basic decoy hit rate estimate: fraction of wrong keys that give decoy != real.
# If your CSV includes many wrong_key, fake_output for a single cipher with real known, then:
# load the set of fake outputs from CSV (these are outputs from wrong guesses)
fake_outputs = df['fake_output'].astype(str).tolist()

# If you have the real plaintext somewhere (if not, set to example)
real_plain = "MyRealPass"  # set appropriately if known
n = len(fake_outputs)
decoy_count = sum(1 for x in fake_outputs if x != real_plain)
decoy_hit_rate = decoy_count / max(1,n)
print("Decoy hit rate (fraction of wrong guesses producing non-real outputs):", decoy_hit_rate)

# More advanced: attacker confusion under a decision rule
# Suppose attacker uses heuristic: if decrypted output appears in common-password-list -> treat as likely real
WL = os.path.join(PROJECT,"wordlists","slices","rockyou_top_10000.txt")
common = set()
if os.path.exists(WL):
    with open(WL,"r",encoding="utf-8",errors="ignore") as f:
        common = set([l.strip() for l in f if l.strip()])
# attacker marks a guess as 'success' if decrypted string is in 'common' list
false_positives = sum(1 for x in fake_outputs if x in common)
false_positive_rate = false_positives / max(1,n)
print("False-positive rate if attacker uses 'is-in-common-list' heuristic:", false_positive_rate)

# Save simulation summary
with open(os.path.join(PROJECT,"tests","honey","outputs","decoy_hit_summary.txt"), "w") as f:
    f.write(f"decoy_hit_rate={decoy_hit_rate}\n")
    f.write(f"false_positive_rate={false_positive_rate}\n")
print("Saved decoy hit summary.")
